  MODULE('APC6N033.CLW')
UpdateNomor_Batal      PROCEDURE                      !Update the Nomor_Batal File
BrowseNomorBatal       PROCEDURE                      !Browse the Nomor_Batal File
UpdateNomor_SKR        PROCEDURE                      !Update the Nomor_SKR File
BrowseNomorSekarang    PROCEDURE                      !Browse the Nomor_SKR File
UpdateNomorUse         PROCEDURE                      !Update the NomorUse File
  END
