  MODULE('APC6N022.CLW')
BrowseBarangKeluarPerBarang PROCEDURE                 !Browse the GBarang File
SelectJUPF             PROCEDURE                      !Select a JUPF Record
SelectJDokter          PROCEDURE                      !Select a JDokter Record
BrowseJTransaksi       PROCEDURE                      !Browse the JTransaksi File
SelectJPasien          PROCEDURE                      !Select a JPasien Record
  END
