  MODULE('APC6N009.CLW')
BrowseRanapNonBilling  PROCEDURE                      !PAKE TRIGGER - Browse Rawat Inap !!!
Cetak_nota_apotik11    PROCEDURE                      !Report the APHTRANS File
Trig_UpdateRawatInap1  PROCEDURE                      !PAKE TRIGGER - Update Rawat Inap !!!
Trig_UpdateRawatInapDetil1 PROCEDURE                  !Update the APDTRANS File
Trig_UpdateCampur      PROCEDURE                      !Update the APDTcam File
  END
