  MODULE('APC6N066.CLW')
PrintDKBOnline         PROCEDURE                      !Report the INDDKB File
BrowseDKBInstalasi     PROCEDURE                      !Browse the INHDKB File
PrintCetakDBKTidakTerpenuhi PROCEDURE                 !Report the INDDKB File
PrintCetakDBKTerpenuhi PROCEDURE                      !Report the INDDKB File
SelectEtiket1          PROCEDURE                      !Browse the Apetiket File
  END
