  MODULE('APC6N046.CLW')
selectbarangalias      PROCEDURE                      !Browse the GBarangA File
UpdateBarangAlias      PROCEDURE                      !Update the GBarangAlias File
BrowseAliasKodeBarang  PROCEDURE                      !Daftar Barang
BrowsePasienRanap      PROCEDURE                      !Browse the JPasien File
BrowseEmbalase         PROCEDURE                      !Browse the ApEmbalase File
  END
