  MODULE('APC6N003.CLW')
BrowseInputOrderVer    PROCEDURE                      !Bon Permohonan Permintaan Barang
UpdateBPBVer           PROCEDURE                      !Update the GHBPB File
WindowNomorKwitansi    PROCEDURE
PrintKwitansiRajal     PROCEDURE                      !Report the APHTRANS File
Balik                  FUNCTION(String SA),String     !dipakai din proc AngkaTulisan,(untuk membalikan angka)
  END
