  MODULE('APC6N053.CLW')
tb_obat_kontraktor     PROCEDURE                      !Melihat tabel kontraktor
Rubah_obat_kontraktor  PROCEDURE                      !Merubah data obat kontraktor
BrowseObatPerKelompok  PROCEDURE                      !Browse the GBarKel File
BrowsePaketObat        PROCEDURE                      !Browse the ApPaketH File
Lihat_Rubah_Satuan_Brg PROCEDURE                      !Browse the Satuan File
  END
