  MODULE('APC6N071.CLW')
BrowseResepElektronis  PROCEDURE                      !Browse the TBTransResepDokterHeader File
Trig_WindowReturRawatInap PROCEDURE                   !Kembali Obat rawat Inap
Trig_BrowseReturRawatInap PROCEDURE                   !Browse the APHTRANS File
Trig_UpdateReturRawatInapDetil PROCEDURE              !Update the APDTRANS File
Trig_UpdateReturRawatInap PROCEDURE                   !Update the APHTRANS File
  END
