  MODULE('APC6N047.CLW')
UpdateFIFOIN           PROCEDURE                      !Update the AFIFOIN File
BrowseKartuFIFOApotikAll PROCEDURE                    !Browse the AFIFOIN File
PrintInstalasi         PROCEDURE                      !Report the TBinstli File
Tabel_instalasi        PROCEDURE                      !Browse the TBinstli File
UpdateTBinstli         PROCEDURE                      !Update the TBinstli File
  END
