  MODULE('APC6N048.CLW')
UpdateISetupAp         PROCEDURE                      !Update the ISetupAp File
Atur_setup             PROCEDURE                      !Browse the ISetupAp File
UpdateGApotik          PROCEDURE                      !Update the GApotik File
Lihat_apotik           PROCEDURE                      !Melihat tabel GApotik
printkartustok         PROCEDURE(string)              !Laporan barang di sub farmasi
  END
