  MODULE('APC6N007.CLW')
Obat_campur            PROCEDURE                      !Browse the APDTcam File
Trig_UpdateRawatJalanDetil2 PROCEDURE                 !Update the APDTRANS File
SelectJGroupKtr        PROCEDURE                      !Select a JGroupKtr Record
SelectJKontrak         PROCEDURE                      !Browse the JKontrak File
SelectJTransaksi       PROCEDURE                      !Browse the JTransaksi File
  END
