  MODULE('APC6N052.CLW')
Rubah_stok_apotik      PROCEDURE                      !Update the GStokAptk File
tabel_stok_lokal       PROCEDURE                      !Melihat tabel gstokaptk
tambah_obat_cmp        PROCEDURE                      !Tambah obat campur
Pilih_Satuan           PROCEDURE                      !Browse the GSatuan File
Tabel_brg_campur       PROCEDURE                      !Tabel obat campur
  END
