  MODULE('APC6N013.CLW')
UpdateGHBPBMaster      PROCEDURE                      !Update the GHBPBMaster File
BrowseBPBMaster        PROCEDURE                      !Browse the GHBPBMaster File
SelectGBarang          PROCEDURE                      !Select a GBarang Record
UpdateGDBPBMaster      PROCEDURE                      !Update the GDBPBMaster File
SelectBarang           PROCEDURE                      !Daftar Barang
  END
