  MODULE('APC6N051.CLW')
BrowseEtiket           PROCEDURE                      !Browse the Apetiket File
BrowseEtiket2          PROCEDURE                      !Browse the Apetiket1 File
UpdateGStokAptk        PROCEDURE                      !Update the GStokAptk File
Lihat_stok_tempat_lain PROCEDURE                      !Daftar Stok Apotik
Cari_diGbarang         PROCEDURE                      !Cari di tabel GBarang
  END
