  MODULE('APC6N070.CLW')
UpdateApNotaObat       PROCEDURE                      !Update the ApNotaObat File
SelectAPHTRANS         PROCEDURE                      !Select a APHTRANS Record
BrowseNotaObatPegawai  PROCEDURE                      !Browse the ApNotaObat File
BrowseApNotaManual     PROCEDURE                      !Browse the ApNotaManual File
UpdateApNotaManual     PROCEDURE                      !Update the ApNotaManual File
  END
