  MODULE('APC6N065.CLW')
Trig_UpdateAptoInHe1   PROCEDURE                      !PAKE TRIGGER - Update Keluar Ruangan !!!
SelectDKBInstalasi     PROCEDURE                      !Browse the INHDKB File
UpdateAptoInDe         PROCEDURE                      !Update the AptoInDe File
cetak_tran_ruang1      PROCEDURE                      !laporan sbbk ke instalasi
cetak_tran_ruang1_retur PROCEDURE                     !laporan sbbk ke instalasi
  END
