  MODULE('APC6N006.CLW')
SelectDokter           PROCEDURE                      !Browse the JDokter File
SelectJTransaksiMR     PROCEDURE                      !Browse the JTransaksi File
SelectJTransaksiMRPengatur PROCEDURE                  !Browse the JTransaksi File
cari_brg_lokal4        PROCEDURE                      !Browse the GBarang File
UpdateAPDTcam          PROCEDURE                      !Update the APDTcam File
  END
