  MODULE('APC6N068.CLW')
PrintEtiketRanap       PROCEDURE                      !Report the APDTRANS File
PrintEtiketRanap1struk PROCEDURE                      !Report the APDTRANS File
PrintEtiketRanapItem   PROCEDURE                      !Report the APDTRANS File
PrintEtiketRanapItemZebra PROCEDURE                   !Report the APDTRANS File
PrintEtiketRanapZebra  PROCEDURE                      !Report the APDTRANS File
  END
