  MODULE('APC6N069.CLW')
CetakKeSumedang        PROCEDURE                      !Report the AptoInSmdD File
BrowseKeluarKeSumedang PROCEDURE                      !Browse the AptoInSmdH File
CetakReturDrSumedang   PROCEDURE                      !Report the AptoInSmdD File
UpdateAptoInSmdD       PROCEDURE                      !Update the AptoInSmdD File
UpdateAptoInSmdH       PROCEDURE                      !Update the AptoInSmdH File
  END
