  MODULE('APC6N067.CLW')
UpdateEtiketTrans      PROCEDURE                      !Update the APDTRANS File
SelectEtiket2          PROCEDURE                      !Browse the Apetiket File
BrowseEtiketTrans      PROCEDURE                      !NEW NUMBER !!!
PrintEtiketRajal1struk PROCEDURE                      !Report the APDTRANS File
PrintEtiketRajalItem   PROCEDURE                      !Report the APDTRANS File
  END
